/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandsignup;

/**
 *
 * @author JORDY
 */
public class AdminLibrary extends javax.swing.JFrame {

    /**
     * Creates new form AdminLibrary
     */
    public AdminLibrary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        inputnomahasiswa6 = new javax.swing.JTextField();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        btn_LihatKodeMahasiswa6 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        txt_kode_buku6 = new javax.swing.JTextField();
        btn_LihatKodeBuku6 = new javax.swing.JLabel();
        btn_delete6 = new javax.swing.JButton();
        btn_reset6 = new javax.swing.JButton();
        btn_simpan6 = new javax.swing.JButton();
        btn_sudahkembali6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel80.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel80.setText("Loan");

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel81.setText("Books");

        jLabel82.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel82.setText("Student Data");

        jLabel83.setText("Student ID :");

        inputnomahasiswa6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        inputnomahasiswa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputnomahasiswa6ActionPerformed(evt);
            }
        });

        jLabel84.setText("Loan Date :");

        jLabel85.setText("Automatically");

        jLabel86.setText("Status :");

        jLabel87.setText("Automatically");

        jLabel88.setText("Returned date :");

        jLabel89.setText("Automatically");

        btn_LihatKodeMahasiswa6.setText("See list of student codes");
        btn_LihatKodeMahasiswa6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_LihatKodeMahasiswa6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_LihatKodeMahasiswa6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LihatKodeMahasiswa6MouseClicked(evt);
            }
        });

        jLabel90.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel90.setText("Book Data");

        jLabel91.setText("Please enter the Book Code Book :");

        jLabel92.setText("Book Code : ");

        txt_kode_buku6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_kode_buku6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kode_buku6ActionPerformed(evt);
            }
        });

        btn_LihatKodeBuku6.setText("Lihat Daftar Kode Buku");
        btn_LihatKodeBuku6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_LihatKodeBuku6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_LihatKodeBuku6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LihatKodeBuku6MouseClicked(evt);
            }
        });

        btn_delete6.setText("Delete");
        btn_delete6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete6ActionPerformed(evt);
            }
        });

        btn_reset6.setText("Reset");
        btn_reset6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reset6ActionPerformed(evt);
            }
        });

        btn_simpan6.setText("Save");
        btn_simpan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan6ActionPerformed(evt);
            }
        });

        btn_sudahkembali6.setText("Mark as Returned (Update)");
        btn_sudahkembali6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sudahkembali6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inputnomahasiswa6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_LihatKodeMahasiswa6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_delete6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_reset6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_simpan6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_sudahkembali6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel84)
                                    .addComponent(jLabel86)
                                    .addComponent(jLabel88))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel85)
                                    .addComponent(jLabel87)
                                    .addComponent(jLabel89))))
                        .addContainerGap(40, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel90, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel92, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_kode_buku6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel91, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addComponent(btn_LihatKodeBuku6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel83)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputnomahasiswa6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel84)
                    .addComponent(jLabel85))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel86)
                    .addComponent(jLabel87))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel88)
                    .addComponent(jLabel89))
                .addGap(10, 10, 10)
                .addComponent(btn_LihatKodeMahasiswa6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(btn_delete6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reset6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_simpan6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_sudahkembali6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(293, 293, 293)
                    .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel91)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel92)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txt_kode_buku6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addComponent(btn_LihatKodeBuku6)
                    .addContainerGap(293, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(21, 51, 72));
        jPanel2.setPreferredSize(new java.awt.Dimension(1120, 100));

        jLabel93.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(255, 255, 255));
        jLabel93.setText("Admin Library");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel93)
                .addContainerGap(780, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel93)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1120, 610));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Major", "Book Code", "Book Title", "Author", "Loan Date", "Status", "Return Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputnomahasiswa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputnomahasiswa6ActionPerformed
        cari_mahasiswa();
    }//GEN-LAST:event_inputnomahasiswa6ActionPerformed

    private void btn_LihatKodeMahasiswa6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LihatKodeMahasiswa6MouseClicked
        // TODO add your handling code here:
        xDaftarKodeMahasiswa xkode = new xDaftarKodeMahasiswa();
        xkode.setLocationRelativeTo(null);
        xkode.setVisible(true);
    }//GEN-LAST:event_btn_LihatKodeMahasiswa6MouseClicked

    private void txt_kode_buku6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kode_buku6ActionPerformed
        // TODO add your handling code here:
        cari_buku();
    }//GEN-LAST:event_txt_kode_buku6ActionPerformed

    private void btn_LihatKodeBuku6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LihatKodeBuku6MouseClicked
        // TODO add your handling code here:
        xDaftarKode xkode = new xDaftarKode();
        xkode.setLocationRelativeTo(null);
        xkode.setVisible(true);
    }//GEN-LAST:event_btn_LihatKodeBuku6MouseClicked

    private void btn_delete6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete6ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel x = (DefaultTableModel) tb_peminjaman.getModel();
        int baris = tb_peminjaman.getSelectedRow();
        String no_mhs = x.getValueAt(baris, 0).toString();
        Connection con = new koneksi_2().getConnection();
        String nama = x.getValueAt(baris, 1).toString();
        String judul = x.getValueAt(baris, 4).toString();

        String kodeunik = nama + judul;
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data Mahasiswa  :" + no_mhs + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                //panggil method koneksi
                System.out.println(kodeunik);
                String sql = "delete from tb_peminjaman where idpeminjaman ='" + kodeunik + "'";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil di hapus");
                x.setRowCount(0);
                tampil_tb_peminjaman();
                reset();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal di hapus");
            }
        }
    }//GEN-LAST:event_btn_delete6ActionPerformed

    private void btn_reset6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reset6ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btn_reset6ActionPerformed

    private void btn_simpan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan6ActionPerformed
        method_varinsert();
    }//GEN-LAST:event_btn_simpan6ActionPerformed

    private void btn_sudahkembali6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sudahkembali6ActionPerformed
        // TODO add your handling code here:
        Connection con = new koneksi_2().getConnection();
        int baris = tb_peminjaman.getSelectedRow();

        String kode_buku = String.valueOf(tb_peminjaman.getValueAt(baris, 3));
        String statusnya = String.valueOf(tb_peminjaman.getValueAt(baris, 8));

        if (statusnya.equals("Dikembalikan")) {
            JOptionPane.showMessageDialog(null, "Buku Sudah Dikembalikan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String nama, no_mhs, tempat_lahir, tanggal_lahir, jurusan, tanggal_masuk;

            try {
                String sqli = "select * from tb_mahasiswa order by no_mhs asc";
                java.sql.Statement stat = con.createStatement();
                java.sql.ResultSet hasil = stat.executeQuery(sqli);
                while (hasil.next()) {
                    no_mhs = hasil.getString("no_mhs");
                    nama = hasil.getString("nama");
                    tempat_lahir = hasil.getString("tempat_lahir");
                    tanggal_lahir = hasil.getString("tanggal_lahir");
                    jurusan = hasil.getString("jurusan");
                    tanggal_masuk = hasil.getString("tanggal_masuk");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            int stokx = 0;
            int dipinjam = 0;
            int dirak = 0;
            int jumlahpinjaman = 0;
            try {
                String sql = "SELECT `kode_buku`, `judul_buku`, `tanggal_terbit`, `pengarang`, `jenis_buku`, `stok`, `dipinjam`, `di_rak`, `dipinjam_berapa_kali` FROM `tb_buku` WHERE `kode_buku`='" + kode_buku + "'";
                java.sql.Statement stat = con.createStatement();
                java.sql.ResultSet hasil = stat.executeQuery(sql);
                while (hasil.next()) {
                    stokx = hasil.getInt("stok");
                    dipinjam = hasil.getInt("dipinjam");
                    dirak = hasil.getInt("di_rak");
                    jumlahpinjaman = hasil.getInt("dipinjam_berapa_kali");
                }
            } catch (Exception e) {
                System.out.println(e);
                System.out.println("GAGAL SELECT TB BUKU ( RETREIVE )");
                JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

            String tanggalkembali = new SimpleDateFormat("dd-MM-yyyy").format(new java.util.Date());
            String bulankembali = new SimpleDateFormat("MM-yyyy").format(new java.util.Date());
            String tahunkembali = new SimpleDateFormat("yyyy").format(new java.util.Date());
            String jamkembali = new SimpleDateFormat("hh:mm:ss").format(new java.util.Date());
            int satu = 1;
            String jdul = String.valueOf(tb_peminjaman.getValueAt(baris, 4));
            String namapeminjam = String.valueOf(tb_peminjaman.getValueAt(baris, 1));
            String unik = namapeminjam+jdul;
            try {System.out.println(unik);
                String sql = "UPDATE `tb_buku` SET `dipinjam`=?,`di_rak`=?,`dipinjam_berapa_kali`=? WHERE `kode_buku`='" + kode_buku + "'";
                String sqla = "UPDATE `tb_peminjaman` SET `status`=?,`tanggal_kembali`=?,`tahun_kembali`=?,`jam_kembali`=?,`bulan_kembali`=? WHERE `idpeminjaman`='" + unik +"'";
                PreparedStatement stat = (PreparedStatement) con.prepareStatement(sql);
                PreparedStatement statu = (PreparedStatement) con.prepareStatement(sqla);
                stat.setInt(1, (dipinjam - 1));
                stat.setInt(2, (dirak + 1));
                stat.setInt(3, (jumlahpinjaman + 1));
                statu.setString(1, "Dikembalikan");
                statu.setString(2, tanggalkembali);
                statu.setString(3, tahunkembali);
                statu.setString(4, jamkembali);
                statu.setString(5, bulankembali);
                stat.executeUpdate();
                statu.executeUpdate();
                JOptionPane.showMessageDialog(null, "Berhasil Diupdate", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                reset();
                tampil_tb_peminjaman();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Menyimpan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                System.out.println(e);
            }
            tampil_tb_peminjaman();
        }
    }//GEN-LAST:event_btn_sudahkembali6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLibrary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_LihatKodeBuku;
    private javax.swing.JLabel btn_LihatKodeBuku1;
    private javax.swing.JLabel btn_LihatKodeBuku2;
    private javax.swing.JLabel btn_LihatKodeBuku3;
    private javax.swing.JLabel btn_LihatKodeBuku4;
    private javax.swing.JLabel btn_LihatKodeBuku5;
    private javax.swing.JLabel btn_LihatKodeBuku6;
    private javax.swing.JLabel btn_LihatKodeMahasiswa;
    private javax.swing.JLabel btn_LihatKodeMahasiswa1;
    private javax.swing.JLabel btn_LihatKodeMahasiswa2;
    private javax.swing.JLabel btn_LihatKodeMahasiswa3;
    private javax.swing.JLabel btn_LihatKodeMahasiswa4;
    private javax.swing.JLabel btn_LihatKodeMahasiswa5;
    private javax.swing.JLabel btn_LihatKodeMahasiswa6;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_delete1;
    private javax.swing.JButton btn_delete2;
    private javax.swing.JButton btn_delete3;
    private javax.swing.JButton btn_delete4;
    private javax.swing.JButton btn_delete5;
    private javax.swing.JButton btn_delete6;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_reset1;
    private javax.swing.JButton btn_reset2;
    private javax.swing.JButton btn_reset3;
    private javax.swing.JButton btn_reset4;
    private javax.swing.JButton btn_reset5;
    private javax.swing.JButton btn_reset6;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_simpan1;
    private javax.swing.JButton btn_simpan2;
    private javax.swing.JButton btn_simpan3;
    private javax.swing.JButton btn_simpan4;
    private javax.swing.JButton btn_simpan5;
    private javax.swing.JButton btn_simpan6;
    private javax.swing.JButton btn_sudahkembali;
    private javax.swing.JButton btn_sudahkembali1;
    private javax.swing.JButton btn_sudahkembali2;
    private javax.swing.JButton btn_sudahkembali3;
    private javax.swing.JButton btn_sudahkembali4;
    private javax.swing.JButton btn_sudahkembali5;
    private javax.swing.JButton btn_sudahkembali6;
    private javax.swing.JTextField inputnomahasiswa;
    private javax.swing.JTextField inputnomahasiswa1;
    private javax.swing.JTextField inputnomahasiswa2;
    private javax.swing.JTextField inputnomahasiswa3;
    private javax.swing.JTextField inputnomahasiswa4;
    private javax.swing.JTextField inputnomahasiswa5;
    private javax.swing.JTextField inputnomahasiswa6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private org.netbeans.modules.form.InvalidComponent kGradientPanel3;
    private org.netbeans.modules.form.InvalidComponent kGradientPanel4;
    private org.netbeans.modules.form.InvalidComponent kGradientPanel5;
    private org.netbeans.modules.form.InvalidComponent kGradientPanel6;
    private org.netbeans.modules.form.InvalidComponent kGradientPanel7;
    private org.netbeans.modules.form.InvalidComponent kGradientPanel8;
    private javax.swing.JTextField txt_kode_buku;
    private javax.swing.JTextField txt_kode_buku1;
    private javax.swing.JTextField txt_kode_buku2;
    private javax.swing.JTextField txt_kode_buku3;
    private javax.swing.JTextField txt_kode_buku4;
    private javax.swing.JTextField txt_kode_buku5;
    private javax.swing.JTextField txt_kode_buku6;
    // End of variables declaration//GEN-END:variables
}
