/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

/**
 *
 * @author ASUS
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class form_buku extends javax.swing.JPanel {
    
    public Statement st;
    public ResultSet rs;
    public Integer id;
    
    Connection cn = config.koneksi.getConnection();
    
    private void clicked(){
        btn_cancel.setVisible(true);
        btn_delete.setVisible(true);
        lab_id.setVisible(true);
        btn_add.setText("EDIT");
    }
    private void notClicked(){
        btn_cancel.setVisible(false);
        btn_delete.setVisible(false);
        lab_id.setVisible(false);
        btn_add.setText("ADD");
    }
    
    private void clear(){
        txt_title.setText("");
        txt_authors.setText("");
        txt_published.setText(""); 
        txt_stock.setText("");
        lab_id.setVisible(false);
    }
    private void display(){
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM books");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Title");
            model.addColumn("Author");          
            model.addColumn("Published");
            model.addColumn("Category");
            model.addColumn("Stock");
            
            model.getDataVector().removeAllElements();
            model.fireTableChanged(null);
            model.setRowCount(0);
            while(rs.next()){
            Object[]data = {
                rs.getString("book_id"),
                rs.getString("title"),
                rs.getString("author"),
                rs.getString("published"),
                rs.getString("category"),
                rs.getString("stock")          
            };
            model.addRow(data);
            tb_book.setModel(model);
            }
        } catch (Exception e) {
        }
    }

        public form_buku() {
        initComponents();
        notClicked();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        data_buku = new javax.swing.JPanel();
        table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_book = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        tambah_buku = new javax.swing.JPanel();
        form = new javax.swing.JPanel();
        txt_title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_authors = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_published = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_category = new javax.swing.JComboBox<>();
        txt_stock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lab_id = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_save = new javax.swing.JButton();
        btn_cancel1 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        data_buku.setBackground(new java.awt.Color(255, 255, 255));

        table.setBackground(new java.awt.Color(255, 255, 255));
        table.setLayout(new java.awt.CardLayout());

        tb_book.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_book.getTableHeader().setResizingAllowed(false);
        tb_book.getTableHeader().setReorderingAllowed(false);
        tb_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_bookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_book);

        table.add(jScrollPane1, "card2");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btn_add.setBackground(new java.awt.Color(0, 51, 102));
        btn_add.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("ADD");
        btn_add.setPreferredSize(new java.awt.Dimension(80, 50));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add);

        btn_cancel.setBackground(new java.awt.Color(153, 0, 51));
        btn_cancel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel);

        btn_delete.setBackground(new java.awt.Color(153, 0, 51));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);

        javax.swing.GroupLayout data_bukuLayout = new javax.swing.GroupLayout(data_buku);
        data_buku.setLayout(data_bukuLayout);
        data_bukuLayout.setHorizontalGroup(
            data_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_bukuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(data_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(data_bukuLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(396, Short.MAX_VALUE))))
        );
        data_bukuLayout.setVerticalGroup(
            data_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_bukuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE))
        );

        mainPanel.add(data_buku, "card2");

        tambah_buku.setBackground(new java.awt.Color(255, 255, 255));

        form.setBackground(new java.awt.Color(255, 255, 255));

        txt_title.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        txt_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_titleActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("TITLE");

        txt_authors.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        txt_authors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_authorsActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("AUTHORS");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("PUBLISHED");

        txt_published.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        txt_published.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_publishedActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("CATEGORY");

        cb_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiction", "Non-fiction", "Mystery", "Thriller", "Romance", "Science Fiction (Sci-Fi)", "Fantasy", "Historical Fiction", "Biography", "Autobiography", "Memoir", "Self-help", "Business", "History", "Travel", "Poetry", "Philosophy", "Religion", "Science", "Psychology" }));
        cb_category.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));

        txt_stock.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        txt_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stockActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("STOCK");

        jLabel6.setText("ID :");

        lab_id.setText("id");

        jPanel2.setLayout(new java.awt.GridLayout());

        btn_save.setBackground(new java.awt.Color(0, 51, 102));
        btn_save.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel2.add(btn_save);

        btn_cancel1.setBackground(new java.awt.Color(153, 0, 51));
        btn_cancel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_cancel1.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel1.setText("Cancel");
        btn_cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancel1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cancel1);

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_title)
            .addComponent(txt_authors)
            .addComponent(txt_published)
            .addComponent(cb_category, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txt_stock)
            .addGroup(formLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab_id)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(formLayout.createSequentialGroup()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 529, Short.MAX_VALUE))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lab_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_authors, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_published, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_category, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambah_bukuLayout = new javax.swing.GroupLayout(tambah_buku);
        tambah_buku.setLayout(tambah_bukuLayout);
        tambah_bukuLayout.setHorizontalGroup(
            tambah_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambah_bukuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tambah_bukuLayout.setVerticalGroup(
            tambah_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        mainPanel.add(tambah_buku, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(tambah_buku);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        if(txt_title.getText().equals("")){
        JOptionPane.showMessageDialog(null, "SILAHKAN PILIH DATA");
        }else{
            int jawab = JOptionPane.showConfirmDialog(null, "LANJUTKAN UNTUK MENGHAPUS DATA !","KONFRIMASI",JOptionPane.YES_NO_OPTION);
            if(jawab == 0 ){
                try {
                    st = cn.createStatement();
                    Object value = tb_book.getValueAt(tb_book.getSelectedRow(), 0);
                    
                    String sql = "DELETE FROM books WHERE book_id = '"+ value.toString() +"' ;";
                    JOptionPane.showMessageDialog(null,"BUKU BERHASIL DIHAPUS");
                    st.executeUpdate(sql);
                    notClicked();
                    display();
                    clear();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null,e);
                }
            
            }
            
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try {
            st = cn.createStatement();
            if(txt_title.equals("") ||txt_authors.equals("") || txt_published.equals("") || txt_stock.equals("")){
                JOptionPane.showMessageDialog(null, "DATA TIDAK BOLEH KOSONG");
                return;
            }
             String title = txt_title.getText();
             String author = txt_authors.getText();
             String published = txt_published.getText();
             String stock = txt_stock.getText(); 
             String category = cb_category.getSelectedItem().toString(); 
            
            if(btn_add.getText() == "ADD"){
                //action tambah data
                String sql = "INSERT INTO books (title, author, published, stock, category) VALUES ('" +
                title + "','" + author + "','" + published + "','" + stock + "','" + category + "')";

                st.executeUpdate(sql);
                notClicked();
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DITAMBAHKAN");
                mainPanel.removeAll();
                mainPanel.repaint();
                mainPanel.revalidate();
                mainPanel.add(data_buku);
                mainPanel.repaint();
                mainPanel.revalidate();
                display();
                clear();
                
            }else{
                //action edit data
               lab_id.setText(tb_book.getValueAt(tb_book.getSelectedRow(),0).toString()); 

                
                String update = "UPDATE books SET title = '"+ title +"' , author = '"+author+"' , published = '"+published+"', stock = '"+stock+"', category = '"+category+"' WHERE book_id = '"+ lab_id.getText() +"'";
                st.executeUpdate(update);
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DI UPDATE");
                mainPanel.removeAll();
                mainPanel.repaint();
                mainPanel.revalidate();
                mainPanel.add(data_buku);
                mainPanel.repaint();
                mainPanel.revalidate();
                display();
                clear();
                notClicked();
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "SILAHKAN MASUKAN DATA DENGAN BENAR");
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancel1ActionPerformed

        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(data_buku);
        mainPanel.repaint();
        mainPanel.revalidate();
        display();
        notClicked();
    }//GEN-LAST:event_btn_cancel1ActionPerformed
 
    private void txt_authorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_authorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_authorsActionPerformed

    private void txt_publishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_publishedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_publishedActionPerformed

    private void txt_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_titleActionPerformed

    private void tb_bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_bookMouseClicked
        // TODO add your handling code here:
        clicked();
        lab_id.setText(tb_book.getValueAt(tb_book.getSelectedRow(),0).toString());
        
        txt_title.setText(tb_book.getValueAt(tb_book.getSelectedRow(),1).toString());
        txt_authors.setText(tb_book.getValueAt(tb_book.getSelectedRow(),2).toString());
        txt_published.setText(tb_book.getValueAt(tb_book.getSelectedRow(),3).toString());
        Object value = tb_book.getValueAt(tb_book.getSelectedRow(), 5);
        if (value != null) {
            txt_stock.setText(value.toString());
        } else {
            // Handle the case where the value is null, such as setting a default text
            txt_stock.setText("N/A");
        }
            cb_category.setSelectedItem(tb_book.getValueAt(tb_book.getSelectedRow(),4).toString());
         
        
    }//GEN-LAST:event_tb_bookMouseClicked

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        notClicked();
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(data_buku);
        mainPanel.repaint();
        mainPanel.revalidate();
        notClicked();
        clear();
        display();
       
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void txt_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_cancel1;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cb_category;
    private javax.swing.JPanel data_buku;
    private javax.swing.JPanel form;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_id;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel table;
    private javax.swing.JPanel tambah_buku;
    private javax.swing.JTable tb_book;
    private javax.swing.JTextField txt_authors;
    private javax.swing.JTextField txt_published;
    private javax.swing.JTextField txt_stock;
    private javax.swing.JTextField txt_title;
    // End of variables declaration//GEN-END:variables
}
